name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Docker Buildx And Push
        run: |-
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --output "type=image,push=true" \
            --tag ${{ secrets.CI_REGISTRY_IMAGE }}:${GITHUB_SHA::8} \
            --tag ${{ secrets.CI_REGISTRY_IMAGE }}:latest \
            --file ./Dockerfile ./
