name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.4", "8.1"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
          
      - name: Docker Buildx And Push
        run: |-
          docker buildx build \
            --build-arg PHP_VERSION=${{ matrix.version }} \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag ${{ secrets.CI_REGISTRY_IMAGE }}:${{ matrix.version }}-fpm \
            --file ./Dockerfile ./
