name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 5 * * 1"
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["7.4", "8.0", "8.1"]
    steps:
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: FPM Build And Push
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          platforms: linux/amd64,linux/arm64
          push: true
          file: /fpm/Dockerfile
          tags: ${{ matrix.version }}-fpm
      - name: Apache Build And Push
        uses: depot/build-push-action@v1
        with:
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          platforms: linux/amd64,linux/arm64
          push: true
          file: /apache/Dockerfile
          tags: ${{ matrix.version }}-apache
