name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 5 * * 1"
jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "7.4", "8.0", "8.1" ]
        server_type: [ "fpm", "apache" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build And Push
        run: |-
          docker buildx build \
            --build-arg PHP_VERSION=${{ matrix.version }} \
            --build-arg SERVER_TYPE=${{ matrix.server_type }} \
            --platform linux/amd64,linux/arm64 \
            --output "type=image,push=true" \
            --tag ${{ secrets.CI_REGISTRY_IMAGE }}:${{ matrix.version }}-${{ matrix.server_type }} \
            --file ./Dockerfile ./
