name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 5 1,15 * *"
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        version: [ "8.0", "8.1", "8.2" ]
        server_type: [ "fpm", "apache" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Depot CLI
        uses: depot/setup-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PASSWORD }}
      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          # if no depot.json file is at the root of your repo, you must specify the project id
          project: 7pgn4b7hbk
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.CI_REGISTRY_IMAGE }}:${{ matrix.version }}-${{ matrix.server_type }}
          build-args: |
            PHP_VERSION=${{ matrix.version }}
            SERVER_TYPE=${{ matrix.server_type }}
